from enum import Enum


class RoleName(str, Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    WAITER = "WAITER"


class TableStatus(str, Enum):
    FREE = "FREE"
    OCCUPIED = "OCCUPIED"
    RESERVED = "RESERVED"


class OrderStatus(str, Enum):
    OPEN = "OPEN"
    PAID = "PAID"
    CANCELLED = "CANCELLED"


class PaymentMethod(str, Enum):
    CASH = "CASH"
    CARD = "CARD"
    TRANSFER = "TRANSFER"


class OrderItemStatus(str, Enum):
    PENDING = "PENDING"
    IN_PREPARATION = "IN_PREPARATION"
    READY = "READY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class ReservationStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    SEATED = "SEATED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class AuditAction(str, Enum):
    # Auth
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    # Users
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_PIN_CHANGED = "USER_PIN_CHANGED"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"
    # Catalog
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_PRICE_UPDATED = "PRODUCT_PRICE_UPDATED"
    PRODUCT_TOGGLED = "PRODUCT_TOGGLED"
    MODIFIER_CREATED = "MODIFIER_CREATED"
    MODIFIER_UPDATED = "MODIFIER_UPDATED"
    MODIFIER_DELETED = "MODIFIER_DELETED"
    # Tax
    TAX_RATE_CREATED = "TAX_RATE_CREATED"
    TAX_RATE_UPDATED = "TAX_RATE_UPDATED"
    TAX_RATE_DEACTIVATED = "TAX_RATE_DEACTIVATED"
    TAX_RATE_DEFAULT_CHANGED = "TAX_RATE_DEFAULT_CHANGED"
    # Orders
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_ITEM_ADDED = "ORDER_ITEM_ADDED"
    ORDER_ITEM_REMOVED = "ORDER_ITEM_REMOVED"
    ORDER_ITEM_UPDATED = "ORDER_ITEM_UPDATED"
    ORDER_PAID = "ORDER_PAID"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    DISCOUNT_APPLIED = "DISCOUNT_APPLIED"
    TABLE_ASSIGNED = "TABLE_ASSIGNED"
    TABLE_RELEASED = "TABLE_RELEASED"
    # Reservations
    RESERVATION_CREATED = "RESERVATION_CREATED"
    RESERVATION_UPDATED = "RESERVATION_UPDATED"
    RESERVATION_CANCELLED = "RESERVATION_CANCELLED"
    RESERVATION_SEATED = "RESERVATION_SEATED"
    RESERVATION_NO_SHOW = "RESERVATION_NO_SHOW"
